apiVersion: web.azure.m.upbound.io/v1beta1
kind: ServicePlan
metadata:
  annotations:
    meta.upbound.io/example-id: web/v1beta1/serviceplan
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    location: West Europe
    osType: Linux
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    skuName: P1v2

---

apiVersion: azure.m.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: web/v1beta1/serviceplan
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    location: West Europe
