apiVersion: devices.azure.m.upbound.io/v1beta1
kind: IOTHubDPS
metadata:
  annotations:
    meta.upbound.io/example-id: devices/v1beta1/iothubdps
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    allocationPolicy: Hashed
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    sku:
    - capacity: "1"
      name: S1

---

apiVersion: azure.m.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: devices/v1beta1/iothubdps
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    location: West Europe
