apiVersion: dataprotection.azure.upbound.io/v1beta1
kind: BackupInstanceKubernetesCluster
metadata:
  annotations:
    meta.upbound.io/example-id: dataprotection/v1beta1/backupinstancekubernetescluster
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    backupDatasourceParameters:
    - clusterScopedResourcesEnabled: true
      excludedNamespaces:
      - test-excluded-namespaces
      excludedResourceTypes:
      - exvolumesnapshotcontents.snapshot.storage.k8s.io
      includedNamespaces:
      - test-included-namespaces
      includedResourceTypes:
      - involumesnapshotcontents.snapshot.storage.k8s.io
      labelSelectors:
      - kubernetes.io/metadata.name:test
      volumeSnapshotEnabled: true
    backupPolicyIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    kubernetesClusterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    location: West Europe
    snapshotResourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: snap
    vaultIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: dataprotection.azure.upbound.io/v1beta1
kind: BackupPolicyKubernetesCluster
metadata:
  annotations:
    meta.upbound.io/example-id: dataprotection/v1beta1/backupinstancekubernetescluster
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    backupRepeatingTimeIntervals:
    - R/2023-05-23T02:30:00+00:00/P1W
    defaultRetentionRule:
    - lifeCycle:
      - dataStoreType: OperationalStore
        duration: P14D
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    retentionRule:
    - criteria:
      - daysOfWeek:
        - Thursday
        monthsOfYear:
        - November
        scheduledBackupTimes:
        - "2023-05-23T02:30:00Z"
        weeksOfMonth:
        - First
      lifeCycle:
      - dataStoreType: OperationalStore
        duration: P84D
      name: Daily
      priority: 25
    vaultNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: dataprotection.azure.upbound.io/v1beta2
kind: BackupVault
metadata:
  annotations:
    meta.upbound.io/example-id: dataprotection/v1beta1/backupinstancekubernetescluster
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    datastoreType: VaultStore
    identity:
    - type: SystemAssigned
    location: West Europe
    redundancy: LocallyRedundant
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: containerservice.azure.upbound.io/v1beta2
kind: KubernetesCluster
metadata:
  annotations:
    meta.upbound.io/example-id: dataprotection/v1beta1/backupinstancekubernetescluster
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    defaultNodePool:
    - enableHostEncryption: true
      name: default
      nodeCount: 1
      vmSize: Standard_DS2_v2
    dnsPrefix: dns
    identity:
    - type: SystemAssigned
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: containerservice.azure.upbound.io/v1beta1
kind: KubernetesClusterExtension
metadata:
  annotations:
    meta.upbound.io/example-id: dataprotection/v1beta1/backupinstancekubernetescluster
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    clusterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    configurationSettings:
      configuration.backupStorageLocation.bucket: example
      configuration.backupStorageLocation.config.resourceGroup: example
      configuration.backupStorageLocation.config.storageAccount: example
      configuration.backupStorageLocation.config.subscriptionId: ${data.azurerm_client_config.current.subscription_id}
      credentials.tenantId: ${data.azurerm_client_config.current.tenant_id}
    extensionType: Microsoft.DataProtection.Kubernetes
    releaseNamespace: dataprotection-microsoft
    releaseTrain: stable

---

apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: dataprotection/v1beta1/backupinstancekubernetescluster
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe

---

apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: dataprotection/v1beta1/backupinstancekubernetescluster
  labels:
    testing.upbound.io/example-name: snap
  name: snap
spec:
  forProvider:
    location: West Europe

---

apiVersion: authorization.azure.upbound.io/v1beta1
kind: RoleAssignment
metadata:
  annotations:
    meta.upbound.io/example-id: dataprotection/v1beta1/backupinstancekubernetescluster
  labels:
    testing.upbound.io/example-name: cluster_msi_contributor_on_snap_rg
  name: cluster-msi-contributor-on-snap-rg
spec:
  forProvider:
    principalId: ${azurerm_kubernetes_cluster.example.identity[0].principal_id}
    roleDefinitionName: Contributor
    scope: ${azurerm_resource_group.snap.id}

---

apiVersion: authorization.azure.upbound.io/v1beta1
kind: RoleAssignment
metadata:
  annotations:
    meta.upbound.io/example-id: dataprotection/v1beta1/backupinstancekubernetescluster
  labels:
    testing.upbound.io/example-name: extension_and_storage_account_permission
  name: extension-and-storage-account-permission
spec:
  forProvider:
    principalId: ${azurerm_kubernetes_cluster_extension.example.aks_assigned_identity[0].principal_id}
    roleDefinitionName: Storage Account Contributor
    scope: ${azurerm_storage_account.example.id}

---

apiVersion: authorization.azure.upbound.io/v1beta1
kind: RoleAssignment
metadata:
  annotations:
    meta.upbound.io/example-id: dataprotection/v1beta1/backupinstancekubernetescluster
  labels:
    testing.upbound.io/example-name: vault_msi_read_on_cluster
  name: vault-msi-read-on-cluster
spec:
  forProvider:
    principalId: ${azurerm_data_protection_backup_vault.example.identity[0].principal_id}
    roleDefinitionName: Reader
    scope: ${azurerm_kubernetes_cluster.example.id}

---

apiVersion: authorization.azure.upbound.io/v1beta1
kind: RoleAssignment
metadata:
  annotations:
    meta.upbound.io/example-id: dataprotection/v1beta1/backupinstancekubernetescluster
  labels:
    testing.upbound.io/example-name: vault_msi_read_on_snap_rg
  name: vault-msi-read-on-snap-rg
spec:
  forProvider:
    principalId: ${azurerm_data_protection_backup_vault.example.identity[0].principal_id}
    roleDefinitionName: Reader
    scope: ${azurerm_resource_group.snap.id}

---

apiVersion: storage.azure.upbound.io/v1beta2
kind: Account
metadata:
  annotations:
    meta.upbound.io/example-id: dataprotection/v1beta1/backupinstancekubernetescluster
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    accountReplicationType: LRS
    accountTier: Standard
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: storage.azure.upbound.io/v1beta1
kind: Container
metadata:
  annotations:
    meta.upbound.io/example-id: dataprotection/v1beta1/backupinstancekubernetescluster
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    containerAccessType: private
    storageAccountNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
