apiVersion: servicebus.azure.upbound.io/v1beta1
kind: Queue
metadata:
  annotations:
    meta.upbound.io/example-id: servicebus/v1beta1/queue
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    namespaceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    partitioningEnabled: true

---

apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: servicebus/v1beta1/queue
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe

---

apiVersion: servicebus.azure.upbound.io/v1beta2
kind: ServiceBusNamespace
metadata:
  annotations:
    meta.upbound.io/example-id: servicebus/v1beta1/queue
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    sku: Standard
    tags:
      source: terraform
