apiVersion: network.azure.m.upbound.io/v1beta1
kind: ExpressRouteCircuit
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1beta1/expressroutecircuit
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    bandwidthInMbps: 50
    location: West Europe
    peeringLocation: Silicon Valley
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    serviceProviderName: Equinix
    sku:
    - family: MeteredData
      tier: Standard
    tags:
      environment: Production

---

apiVersion: azure.m.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1beta1/expressroutecircuit
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    location: West Europe
