apiVersion: cosmosdb.azure.m.upbound.io/v1beta1
kind: MongoRoleDefinition
metadata:
  annotations:
    meta.upbound.io/example-id: cosmosdb/v1beta1/mongoroledefinition
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    cosmosMongoDatabaseIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: cosmosdb.azure.m.upbound.io/v1beta1
kind: Account
metadata:
  annotations:
    meta.upbound.io/example-id: cosmosdb/v1beta1/mongoroledefinition
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    capabilities:
    - name: EnableMongo
    - name: EnableMongoRoleBasedAccessControl
    consistencyPolicy:
    - consistencyLevel: Strong
    geoLocation:
    - failoverPriority: 0
      location: West Europe
    kind: MongoDB
    location: West Europe
    offerType: Standard
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: cosmosdb.azure.m.upbound.io/v1beta1
kind: MongoDatabase
metadata:
  annotations:
    meta.upbound.io/example-id: cosmosdb/v1beta1/mongoroledefinition
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    accountNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: azure.m.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: cosmosdb/v1beta1/mongoroledefinition
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    location: West Europe
