apiVersion: operationalinsights.azure.m.upbound.io/v1beta1
kind: LogAnalyticsQueryPack
metadata:
  annotations:
    meta.upbound.io/example-id: operationalinsights/v1beta1/loganalyticsquerypack
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: azure.m.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: operationalinsights/v1beta1/loganalyticsquerypack
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    location: West Europe
