apiVersion: cdn.azure.upbound.io/v1beta1
kind: FrontdoorSecret
metadata:
  annotations:
    meta.upbound.io/example-id: cdn/v1beta1/frontdoorsecret
    upjet.upbound.io/manual-intervention: "FrontoorSecret requires manual testing because you have to add Access Policy to your azurerm_key_vault for the Microsoft.AzurefrontDoor-Cdn Enterprise Application Object ID."
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    cdnFrontdoorProfileIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    secret:
      customerCertificate:
      - keyVaultCertificateIdSelector:
          matchLabels:
            testing.upbound.io/example-name: example

---

apiVersion: cdn.azure.upbound.io/v1beta1
kind: FrontdoorProfile
metadata:
  annotations:
    meta.upbound.io/example-id: cdn/v1beta1/frontdoorsecret
    upjet.upbound.io/manual-intervention: "FrontoorSecret requires manual testing because you have to add Access Policy to your azurerm_key_vault for the Microsoft.AzurefrontDoor-Cdn Enterprise Application Object ID."
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    skuName: Standard_AzureFrontDoor

---

apiVersion: keyvault.azure.upbound.io/v1beta2
kind: Vault
metadata:
  annotations:
    meta.upbound.io/example-id: cdn/v1beta1/frontdoorsecret
    upjet.upbound.io/manual-intervention: "FrontoorSecret requires manual testing because you have to add Access Policy to your azurerm_key_vault for the Microsoft.AzurefrontDoor-Cdn Enterprise Application Object ID."
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe
    networkAcls:
      bypass: AzureServices
      defaultAction: Deny
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    skuName: premium
    softDeleteRetentionDays: 7
    tenantId: ${data.azurerm_client_config.current.tenant_id}

---

apiVersion: keyvault.azure.upbound.io/v1beta2
kind: Certificate
metadata:
  annotations:
    meta.upbound.io/example-id: cdn/v1beta1/frontdoorsecret
    upjet.upbound.io/manual-intervention: "FrontoorSecret requires manual testing because you have to add Access Policy to your azurerm_key_vault for the Microsoft.AzurefrontDoor-Cdn Enterprise Application Object ID."
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    certificate:
      contentsSecretRef:
        key: example-key
        name: example-secret
        namespace: upbound-system
    keyVaultIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    name: example-cert

---

apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: cdn/v1beta1/frontdoorsecret
    upjet.upbound.io/manual-intervention: "FrontoorSecret requires manual testing because you have to add Access Policy to your azurerm_key_vault for the Microsoft.AzurefrontDoor-Cdn Enterprise Application Object ID."
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe
