apiVersion: logic.azure.m.upbound.io/v1beta1
kind: AppTriggerCustom
metadata:
  annotations:
    meta.upbound.io/example-id: logic/v1beta1/apptriggercustom
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    body: |
      {
        "recurrence": {
          "frequency": "Day",
          "interval": 1
        },
        "type": "Recurrence"
      }
    logicAppIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: logic.azure.m.upbound.io/v1beta1
kind: AppWorkflow
metadata:
  annotations:
    meta.upbound.io/example-id: logic/v1beta1/apptriggercustom
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: azure.m.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: logic/v1beta1/apptriggercustom
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    location: West Europe
