apiVersion: compute.azure.m.upbound.io/v1beta1
kind: DiskAccess
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/diskaccess
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
