apiVersion: datafactory.azure.m.upbound.io/v1beta1
kind: DataSetCosmosDBSQLAPI
metadata:
  annotations:
    meta.upbound.io/example-id: datafactory/v1beta1/datasetcosmosdbsqlapi
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    collectionName: bar
    dataFactoryIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    linkedServiceNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: datafactory.azure.m.upbound.io/v1beta1
kind: Factory
metadata:
  annotations:
    meta.upbound.io/example-id: datafactory/v1beta1/datasetcosmosdbsqlapi
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: datafactory.azure.m.upbound.io/v1beta1
kind: LinkedServiceCosmosDB
metadata:
  annotations:
    meta.upbound.io/example-id: datafactory/v1beta1/datasetcosmosdbsqlapi
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    accountEndpoint: ${data.azurerm_cosmosdb_account.example.endpoint}
    dataFactoryIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    database: foo

---

apiVersion: azure.m.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: datafactory/v1beta1/datasetcosmosdbsqlapi
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    location: West Europe
