# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: authorization.azure.upbound.io/v1beta1
kind: PolicyDefinition
metadata:
  annotations:
    meta.upbound.io/example-id: authorization/v1beta1/policydefinition
  labels:
    testing.upbound.io/example-name: policy
  name: policy
spec:
  forProvider:
    displayName: acceptance test policy definition
    metadata: |2+
          {
          "category": "General"
          }

    mode: Indexed
    parameters: "\t{\n    \"allowedLocations\": {\n      \"type\": \"Array\",\n      \"metadata\":
      {\n        \"description\": \"The list of allowed locations for resources.\",\n
      \       \"displayName\": \"Allowed locations\",\n        \"strongType\": \"location\"\n
      \     }\n    }\n  }\n"
    policyRule: "\t{\n    \"if\": {\n      \"not\": {\n        \"field\": \"location\",\n
      \       \"in\": \"[parameters('allowedLocations')]\"\n      }\n    },\n    \"then\":
      {\n      \"effect\": \"audit\"\n    }\n  }\n"
    policyType: Custom
---
apiVersion: management.azure.upbound.io/v1beta1
kind: ManagementGroup
metadata:
  annotations:
    meta.upbound.io/example-id: authorization/v1beta1/policydefinition-management-group
  labels:
    testing.upbound.io/example-name: policydefinition-management-group
  name: policydefinition-management-group
spec:
  forProvider:
    displayName: PolicyDefinitionManagementGroup
---
apiVersion: authorization.azure.upbound.io/v1beta1
kind: PolicyDefinition
metadata:
  annotations:
    meta.upbound.io/example-id: authorization/v1beta1/policydefinition-management-group
  labels:
    testing.upbound.io/example-name: policydefinition-management-group
  name: policydefinition-management-group
spec:
  forProvider:
    displayName: acceptance test policy definition management group
    managementGroupIdSelector:
      matchLabels:
        testing.upbound.io/example-name: policydefinition-management-group
    metadata: |
      {
        "category": "General"
      }
    mode: Indexed
    parameters: |
      {
        "allowedLocations": {
          "type": "Array",
          "metadata": {
            "description": "The list of allowed locations for resources.",
            "displayName": "Allowed locations",
            "strongType": "location"
          }
        }
      }
    policyRule: |
      {
        "if": {
          "not": {
            "field": "location",
            "in": "[parameters('allowedLocations')]"
          }
        },
        "then": {
          "effect": "audit"
        }
      }
    policyType: Custom
