apiVersion: authorization.azure.upbound.io/v1beta1
kind: ResourceGroupPolicyExemption
metadata:
  annotations:
    meta.upbound.io/example-id: authorization/v1beta1/resourcegrouppolicyexemption
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    exemptionCategory: Mitigated
    policyAssignmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    resourceGroupIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: authorization/v1beta1/resourcegrouppolicyexemption
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: westus

---

apiVersion: authorization.azure.upbound.io/v1beta2
kind: ResourceGroupPolicyAssignment
metadata:
  annotations:
    meta.upbound.io/example-id: authorization/v1beta1/resourcegrouppolicyexemption
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    parameters: |
      {
        "listOfAllowedLocations": {
            "value": [
                "westus"
            ]
        }
      }
    policyDefinitionId: "/providers/Microsoft.Authorization/policyDefinitions/e56962a6-4747-49cd-b67b-bf8b01975c4c"
    resourceGroupIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

