apiVersion: apimanagement.azure.m.upbound.io/v1beta1
kind: IdentityProviderMicrosoft
metadata:
  annotations:
    meta.upbound.io/example-id: apimanagement/v1beta1/identityprovidermicrosoft
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    apiManagementNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    clientId: 00000000-0000-0000-0000-000000000000
    clientSecretSecretRef:
      key: example-key
      name: example-secret
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: apimanagement.azure.m.upbound.io/v1beta1
kind: Management
metadata:
  annotations:
    meta.upbound.io/example-id: apimanagement/v1beta1/identityprovidermicrosoft
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    location: West Europe
    publisherEmail: company@terraform.io
    publisherName: My Company
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    skuName: Developer_1

---

apiVersion: azure.m.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: apimanagement/v1beta1/identityprovidermicrosoft
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    location: West Europe
