apiVersion: apimanagement.azure.m.upbound.io/v1beta1
kind: Logger
metadata:
  annotations:
    meta.upbound.io/example-id: apimanagement/v1beta1/logger
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    apiManagementNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    applicationInsights:
    - instrumentationKeySecretRef:
        key: attribute.instrumentation_key
        name: example-application-insights
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    resourceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: apimanagement.azure.m.upbound.io/v1beta1
kind: Management
metadata:
  annotations:
    meta.upbound.io/example-id: apimanagement/v1beta1/logger
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    location: West Europe
    publisherEmail: company@terraform.io
    publisherName: My Company
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    skuName: Developer_1

---

apiVersion: insights.azure.m.upbound.io/v1beta1
kind: ApplicationInsights
metadata:
  annotations:
    meta.upbound.io/example-id: apimanagement/v1beta1/logger
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    applicationType: other
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: azure.m.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: apimanagement/v1beta1/logger
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    location: West Europe
